version: '3.6'
services:
  worker1:
    container_name: reservasi-worker1
    image: reservasi
    depends_on:
      - db
    environment:
      DB_HOST: db
  worker2:
    container_name: reservasi-worker2
    image: reservasi
    depends_on:
      - db
    environment:
      DB_HOST: db
  worker3:
    container_name: reservasi-worker3
    image: reservasi
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    container_name: reservasi-db
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: reservasi
      MYSQL_USER: userawan
      MYSQL_PASSWORD: buayakecil
    volumes:
      - reservasi:/var/lib/mysql
      - ./reservasi/reservasi.sql:/docker-entrypoint-initdb.d/reservasi.sql
  balancer:
    container_name: reservasi-balancer
    image: nginx
    depends_on:
      - worker1
      - worker2
      - worker3
    links:
      - worker1:worker1
      - worker2:worker2
      - worker3:worker3
    ports:
      - 5000:80
    volumes:
      - ./balancer.conf:/etc/nginx/conf.d/default.conf
volumes:
  reservasi:
