#!/usr/bin/env bash

pwd
mkdir redzones/$1

cp -f redzones/.template/Vagrantfile redzones/$1

sed -i "s/ID/$1/g" redzones/$1/Vagrantfile
sed -i "s/IP/$2/g" redzones/$1/Vagrantfile

cd redzones/$1
pwd
vagrant destroy --force && vagrant up
cd ..

echo "$3	IN	A	$2" >> /etc/bind/tekankata/tekankata.com
