# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure ("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "src", "/var/www"
  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 4
  end
end
