# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure (('2')) { |config|
    config.vm.box = 'hashicorp/precise64'
    config.vm.box_check_update = false
    config.vm.network 'forwarded_port', guest: 80, host: 8080
    config.vm.network 'forwarded_port', guest: 3306, host: 6969
    config.vm.synced_folder 'pelatihan-laravel', '/var/www/web'
    config.vm.provision 'shell', path: 'bootstrap.sh'
    
    config.vm.provider ('virtualbox') { |vb|
       vb.memory = 512
       vb.cpus = 2
    }
    
    config.ssh.shell = 'bash -c "BASH_ENV=/etc/profile exec bash"'
}
