# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure (2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.0.2"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 4
  end

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
end
