# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'hashicorp/precise64'
  config.vm.box_check_update = false
  config.vm.network 'forwarded_port', guest: 80, host: 9000

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
    service nginx start
  SHELL

  config.vm.provider('virtualbox') do |vb|
    vb.memory = 512
    vb.cpus = 2
  end
end
