# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
    config.vm.box = 'ubuntu/xenial64'
    config.vm.box_check_update = false
    config.vm.network 'private_network', ip: '192.168.33.12'
    config.vm.synced_folder '~/.ssh', '/home/vagrant/ssh'
    config.vm.provision 'shell', path: '../bootstrap.sh', privileged: false
    
    config.vm.provider 'virtualbox' do |vb|
      vb.name = 'VM 1'
      vb.memory = 256
      vb.cpus = 1
    end
  end