# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.box_check_update = false
  config.vm.network 'public_network', ip: 'IP'
  config.vm.provision 'shell', path: '../../.template/bootstrap.sh'
  config.vm.synced_folder '../../.docker_image', '/home/vagrant/docker_image'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'USERNAME.tekankata.com'
    vb.memory = 512
    vb.cpus = 1
  end
end
