# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'hashicorp/precise64'
  config.vm.box_check_update = false
  config.vm.network 'private_network', ip: '192.168.0.4'
  config.vm.provision 'shell', path: '../bootstrap.sh'

  config.vm.provider('virtualbox') do |vb|
    vb.memory = 512
    vb.cpus = 2
  end
end
