#!/usr/bin/env bash

NODE_DIR=nodes/$2
mkdir -p $NODE_DIR

cp -f .template/Vagrantfile $NODE_DIR
VAGRANTFILE=$NODE_DIR/Vagrantfile
sed -i "s/ID/$1/g" $VAGRANTFILE
sed -i "s/SUBDOMAIN/$2/g" $VAGRANTFILE

cp -f .template/nginx.conf $NODE_DIR
NGINX_CONF=$NODE_DIR/nginx.conf
sed -i "s/ID/$1/g" $NGINX_CONF
sed -i "s/SUBDOMAIN/$2/g" $NGINX_CONF
cat $NGINX_CONF >> /etc/nginx/sites-enabled/tekankata.conf

cd $NODE_DIR
vagrant destroy --force && vagrant up

