#!/usr/bin/env bash

NODE_DIR=nodes/$2
mkdir -p $NODE_DIR

cp -f .template/Vagrantfile $NODE_DIR
echo "$2        IN      A       10.11.12.$1"
VAGRANTFILE=$NODE_DIR/Vagrantfile
sed -i "s/ID/$1/g" $VAGRANTFILE
sed -i "s/IP/10.11.12.$1/g" $VAGRANTFILE
sed -i "s/USERNAME/$2/g" $VAGRANTFILE

cd $NODE_DIR
vagrant destroy --force && vagrant up

echo "$2        IN      A       10.11.12.$1"
echo "$2	IN	A	10.11.12.$1" >> /etc/bind/tekankata/tekankata.com
