# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.box_check_update = false
  config.vm.network 'private_network', ip: '10.11.1.3'
  config.vm.synced_folder '~/.ssh', '/home/vagrant/ssh'
  config.vm.provision 'shell', path: '../../bootstrap.sh', privileged: false
  
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'Worker 1'
    vb.memory = 256
    vb.cpus = 1
  end
end